/*
 * This Hyperlambda snippet demonstrates basic exception handling.
 * The [try] lambda block attempts to throw an exception.
 * The [.catch] lambda block catches the exception and sets [.throws] value to `true`.
 * Expected behavior: [.throws] should be `true` after execution.
 */

.throws:bool:false
try
   throw:foo
.catch
   set-value:x:@.throws
      .:bool:true
