/*
 * This Hyperlambda code demonstrates the use of exception handling.
 * It illustrates a try-catch-finally block where an exception is thrown and caught.
 * The catch block logs an error message, while the finally block executes regardless of an exception.
 */
try
   throw:SomeError
.catch
   log.info:An error occurred! Code 99, 99, 99!
.finally
   log.info:Finally block executed successfully!