/*
 * This example illustrates the use of nested `try` blocks to manage exceptions with varying specificity.
 * The outer `try` block is designed to catch any general exceptions, while the inner `try` block
 * is focused on handling exceptions related to the [io.file.load] operation.
 */

// Temporary node for storing file content
.content-buffer
try
   try
      io.file.load:x:@.path-to-file
      set-value:x:@.content-buffer
         .:x:@io.file.load
   .catch
      log.error:Unable to locate the specified file
.catch
   log.error:An unexpected error was encountered during the file operation.